name: health-ai
channels:
- conda-forge
dependencies:
- python=3.11.14
- pandas=2.3.3
- numpy=2.4.0
- seaborn=0.13.2
- scipy=1.16.3
- scikit-learn=1.8.0
- matplotlib=3.10.8
- joblib=1.5.3
- tqdm=4.67.1
- statsmodels=0.14.6
- pyarrow=22.0.0
- httpx=0.28.1
- uvicorn=0.40.0
- pydantic=2.12.5
- fastapi=0.128.0
- spacy=3.8.11
- nltk=3.9.2
- pytest=9.0.2
- pre-commit=4.5.1
- isort=7.0.0
- black=25.12.0
- mypy=1.19.1
- conda-lock=4.0.0
prefix: C:\Users\ruthy\miniforge3\envs\health-ai
